name: driftscope
channels:
  - conda-forge
dependencies:
  - python=3.11
  - parcels>=3.0
  - copernicusmarine>=2.0
  - cdsapi>=0.7
  - pytmd>=3.0
  - xarray
  - netcdf4
  - zarr
  - numpy
  - pandas
  - matplotlib
  - cartopy
  - streamlit
  - pydeck
  - plotly
  - python-dotenv
  - tqdm
  - scipy
  - scikit-learn
  - rich
  - pip
  - pip:
      - streamlit-folium
      - folium
